// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/transport/internet/tcp/config.proto

package com.v2ray.core.transport.internet.tcp;

public interface ConnectionReuseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.transport.internet.tcp.ConnectionReuse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool enable = 1;</code>
   */
  boolean getEnable();
}
