// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/config.proto

package com.v2ray.core;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033v2ray.com/core/config.proto\022\nv2ray.cor" +
      "e\032(v2ray.com/core/app/proxyman/config.pr" +
      "oto\0320v2ray.com/core/common/serial/typed_" +
      "message.proto\032%v2ray.com/core/transport/" +
      "config.proto\"\366\001\n\006Config\022>\n\007inbound\030\001 \003(\013" +
      "2-.v2ray.core.app.proxyman.InboundHandle" +
      "rConfig\022@\n\010outbound\030\002 \003(\0132..v2ray.core.a" +
      "pp.proxyman.OutboundHandlerConfig\0223\n\003app" +
      "\030\004 \003(\0132&.v2ray.core.common.serial.TypedM" +
      "essage\022/\n\ttransport\030\005 \001(\0132\034.v2ray.core.t",
      "ransport.ConfigJ\004\010\003\020\004*&\n\014ConfigFormat\022\014\n" +
      "\010Protobuf\020\000\022\010\n\004JSON\020\001B%\n\016com.v2ray.coreP" +
      "\001Z\004core\252\002\nV2Ray.Coreb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.v2ray.core.app.proxyman.Config.getDescriptor(),
          com.v2ray.core.common.serial.TypedMessageOuterClass.getDescriptor(),
          com.v2ray.core.transport.ConfigOuterClass.getDescriptor(),
        }, assigner);
    internal_static_v2ray_core_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_Config_descriptor,
        new java.lang.String[] { "Inbound", "Outbound", "App", "Transport", });
    com.v2ray.core.app.proxyman.Config.getDescriptor();
    com.v2ray.core.common.serial.TypedMessageOuterClass.getDescriptor();
    com.v2ray.core.transport.ConfigOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
