// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/proxy/shadowsocks/config.proto

package com.v2ray.core.proxy.shadowsocks;

public final class ConfigProto {
  private ConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code v2ray.core.proxy.shadowsocks.CipherType}
   */
  public enum CipherType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>AES_128_CFB = 1;</code>
     */
    AES_128_CFB(1),
    /**
     * <code>AES_256_CFB = 2;</code>
     */
    AES_256_CFB(2),
    /**
     * <code>CHACHA20 = 3;</code>
     */
    CHACHA20(3),
    /**
     * <code>CHACHA20_IETF = 4;</code>
     */
    CHACHA20_IETF(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>AES_128_CFB = 1;</code>
     */
    public static final int AES_128_CFB_VALUE = 1;
    /**
     * <code>AES_256_CFB = 2;</code>
     */
    public static final int AES_256_CFB_VALUE = 2;
    /**
     * <code>CHACHA20 = 3;</code>
     */
    public static final int CHACHA20_VALUE = 3;
    /**
     * <code>CHACHA20_IETF = 4;</code>
     */
    public static final int CHACHA20_IETF_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CipherType valueOf(int value) {
      return forNumber(value);
    }

    public static CipherType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return AES_128_CFB;
        case 2: return AES_256_CFB;
        case 3: return CHACHA20;
        case 4: return CHACHA20_IETF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CipherType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CipherType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CipherType>() {
            public CipherType findValueByNumber(int number) {
              return CipherType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.v2ray.core.proxy.shadowsocks.ConfigProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CipherType[] VALUES = values();

    public static CipherType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CipherType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:v2ray.core.proxy.shadowsocks.CipherType)
  }

  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.shadowsocks.Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string password = 1;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 1;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
     */
    int getCipherTypeValue();
    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
     */
    com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType getCipherType();

    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
     */
    int getOtaValue();
    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
     */
    com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth getOta();
  }
  /**
   * Protobuf type {@code v2ray.core.proxy.shadowsocks.Account}
   */
  public  static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v2ray.core.proxy.shadowsocks.Account)
      AccountOrBuilder {
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Account() {
      password_ = "";
      cipherType_ = 0;
      ota_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Account(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              cipherType_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              ota_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_Account_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.class, com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.Builder.class);
    }

    /**
     * Protobuf enum {@code v2ray.core.proxy.shadowsocks.Account.OneTimeAuth}
     */
    public enum OneTimeAuth
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Auto = 0;</code>
       */
      Auto(0),
      /**
       * <code>Disabled = 1;</code>
       */
      Disabled(1),
      /**
       * <code>Enabled = 2;</code>
       */
      Enabled(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Auto = 0;</code>
       */
      public static final int Auto_VALUE = 0;
      /**
       * <code>Disabled = 1;</code>
       */
      public static final int Disabled_VALUE = 1;
      /**
       * <code>Enabled = 2;</code>
       */
      public static final int Enabled_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OneTimeAuth valueOf(int value) {
        return forNumber(value);
      }

      public static OneTimeAuth forNumber(int value) {
        switch (value) {
          case 0: return Auto;
          case 1: return Disabled;
          case 2: return Enabled;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OneTimeAuth>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OneTimeAuth> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OneTimeAuth>() {
              public OneTimeAuth findValueByNumber(int number) {
                return OneTimeAuth.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.getDescriptor().getEnumTypes().get(0);
      }

      private static final OneTimeAuth[] VALUES = values();

      public static OneTimeAuth valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private OneTimeAuth(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:v2ray.core.proxy.shadowsocks.Account.OneTimeAuth)
    }

    public static final int PASSWORD_FIELD_NUMBER = 1;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 1;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CIPHER_TYPE_FIELD_NUMBER = 2;
    private int cipherType_;
    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
     */
    public int getCipherTypeValue() {
      return cipherType_;
    }
    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
     */
    public com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType getCipherType() {
      com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType result = com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType.valueOf(cipherType_);
      return result == null ? com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType.UNRECOGNIZED : result;
    }

    public static final int OTA_FIELD_NUMBER = 3;
    private int ota_;
    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
     */
    public int getOtaValue() {
      return ota_;
    }
    /**
     * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
     */
    public com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth getOta() {
      com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth result = com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth.valueOf(ota_);
      return result == null ? com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, password_);
      }
      if (cipherType_ != com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType.UNKNOWN.getNumber()) {
        output.writeEnum(2, cipherType_);
      }
      if (ota_ != com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth.Auto.getNumber()) {
        output.writeEnum(3, ota_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, password_);
      }
      if (cipherType_ != com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cipherType_);
      }
      if (ota_ != com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth.Auto.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, ota_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.v2ray.core.proxy.shadowsocks.ConfigProto.Account)) {
        return super.equals(obj);
      }
      com.v2ray.core.proxy.shadowsocks.ConfigProto.Account other = (com.v2ray.core.proxy.shadowsocks.ConfigProto.Account) obj;

      boolean result = true;
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && cipherType_ == other.cipherType_;
      result = result && ota_ == other.ota_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + CIPHER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + cipherType_;
      hash = (37 * hash) + OTA_FIELD_NUMBER;
      hash = (53 * hash) + ota_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.v2ray.core.proxy.shadowsocks.ConfigProto.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v2ray.core.proxy.shadowsocks.Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v2ray.core.proxy.shadowsocks.Account)
        com.v2ray.core.proxy.shadowsocks.ConfigProto.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_Account_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.class, com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.Builder.class);
      }

      // Construct using com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        password_ = "";

        cipherType_ = 0;

        ota_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_Account_descriptor;
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.Account getDefaultInstanceForType() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.getDefaultInstance();
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.Account build() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.Account buildPartial() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.Account result = new com.v2ray.core.proxy.shadowsocks.ConfigProto.Account(this);
        result.password_ = password_;
        result.cipherType_ = cipherType_;
        result.ota_ = ota_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.v2ray.core.proxy.shadowsocks.ConfigProto.Account) {
          return mergeFrom((com.v2ray.core.proxy.shadowsocks.ConfigProto.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.v2ray.core.proxy.shadowsocks.ConfigProto.Account other) {
        if (other == com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.getDefaultInstance()) return this;
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.cipherType_ != 0) {
          setCipherTypeValue(other.getCipherTypeValue());
        }
        if (other.ota_ != 0) {
          setOtaValue(other.getOtaValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.Account parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.v2ray.core.proxy.shadowsocks.ConfigProto.Account) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 1;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 1;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private int cipherType_ = 0;
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
       */
      public int getCipherTypeValue() {
        return cipherType_;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
       */
      public Builder setCipherTypeValue(int value) {
        cipherType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
       */
      public com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType getCipherType() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType result = com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType.valueOf(cipherType_);
        return result == null ? com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
       */
      public Builder setCipherType(com.v2ray.core.proxy.shadowsocks.ConfigProto.CipherType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cipherType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.CipherType cipher_type = 2;</code>
       */
      public Builder clearCipherType() {
        
        cipherType_ = 0;
        onChanged();
        return this;
      }

      private int ota_ = 0;
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
       */
      public int getOtaValue() {
        return ota_;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
       */
      public Builder setOtaValue(int value) {
        ota_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
       */
      public com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth getOta() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth result = com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth.valueOf(ota_);
        return result == null ? com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
       */
      public Builder setOta(com.v2ray.core.proxy.shadowsocks.ConfigProto.Account.OneTimeAuth value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        ota_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .v2ray.core.proxy.shadowsocks.Account.OneTimeAuth ota = 3;</code>
       */
      public Builder clearOta() {
        
        ota_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:v2ray.core.proxy.shadowsocks.Account)
    }

    // @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.Account)
    private static final com.v2ray.core.proxy.shadowsocks.ConfigProto.Account DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.v2ray.core.proxy.shadowsocks.ConfigProto.Account();
    }

    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Account(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    public com.v2ray.core.proxy.shadowsocks.ConfigProto.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.shadowsocks.ServerConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool udp_enabled = 1;</code>
     */
    boolean getUdpEnabled();

    /**
     * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
     */
    com.v2ray.core.common.protocol.UserProto.User getUser();
    /**
     * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
     */
    com.v2ray.core.common.protocol.UserProto.UserOrBuilder getUserOrBuilder();
  }
  /**
   * Protobuf type {@code v2ray.core.proxy.shadowsocks.ServerConfig}
   */
  public  static final class ServerConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v2ray.core.proxy.shadowsocks.ServerConfig)
      ServerConfigOrBuilder {
    // Use ServerConfig.newBuilder() to construct.
    private ServerConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerConfig() {
      udpEnabled_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServerConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              udpEnabled_ = input.readBool();
              break;
            }
            case 18: {
              com.v2ray.core.common.protocol.UserProto.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.v2ray.core.common.protocol.UserProto.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig.class, com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig.Builder.class);
    }

    public static final int UDP_ENABLED_FIELD_NUMBER = 1;
    private boolean udpEnabled_;
    /**
     * <code>optional bool udp_enabled = 1;</code>
     */
    public boolean getUdpEnabled() {
      return udpEnabled_;
    }

    public static final int USER_FIELD_NUMBER = 2;
    private com.v2ray.core.common.protocol.UserProto.User user_;
    /**
     * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
     */
    public com.v2ray.core.common.protocol.UserProto.User getUser() {
      return user_ == null ? com.v2ray.core.common.protocol.UserProto.User.getDefaultInstance() : user_;
    }
    /**
     * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
     */
    public com.v2ray.core.common.protocol.UserProto.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (udpEnabled_ != false) {
        output.writeBool(1, udpEnabled_);
      }
      if (user_ != null) {
        output.writeMessage(2, getUser());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (udpEnabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, udpEnabled_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig)) {
        return super.equals(obj);
      }
      com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig other = (com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig) obj;

      boolean result = true;
      result = result && (getUdpEnabled()
          == other.getUdpEnabled());
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UDP_ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUdpEnabled());
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v2ray.core.proxy.shadowsocks.ServerConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v2ray.core.proxy.shadowsocks.ServerConfig)
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig.class, com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig.Builder.class);
      }

      // Construct using com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        udpEnabled_ = false;

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor;
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig getDefaultInstanceForType() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig.getDefaultInstance();
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig build() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig buildPartial() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig result = new com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig(this);
        result.udpEnabled_ = udpEnabled_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig) {
          return mergeFrom((com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig other) {
        if (other == com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig.getDefaultInstance()) return this;
        if (other.getUdpEnabled() != false) {
          setUdpEnabled(other.getUdpEnabled());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean udpEnabled_ ;
      /**
       * <code>optional bool udp_enabled = 1;</code>
       */
      public boolean getUdpEnabled() {
        return udpEnabled_;
      }
      /**
       * <code>optional bool udp_enabled = 1;</code>
       */
      public Builder setUdpEnabled(boolean value) {
        
        udpEnabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool udp_enabled = 1;</code>
       */
      public Builder clearUdpEnabled() {
        
        udpEnabled_ = false;
        onChanged();
        return this;
      }

      private com.v2ray.core.common.protocol.UserProto.User user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.v2ray.core.common.protocol.UserProto.User, com.v2ray.core.common.protocol.UserProto.User.Builder, com.v2ray.core.common.protocol.UserProto.UserOrBuilder> userBuilder_;
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public com.v2ray.core.common.protocol.UserProto.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.v2ray.core.common.protocol.UserProto.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public Builder setUser(com.v2ray.core.common.protocol.UserProto.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public Builder setUser(
          com.v2ray.core.common.protocol.UserProto.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public Builder mergeUser(com.v2ray.core.common.protocol.UserProto.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.v2ray.core.common.protocol.UserProto.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public com.v2ray.core.common.protocol.UserProto.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      public com.v2ray.core.common.protocol.UserProto.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.v2ray.core.common.protocol.UserProto.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>optional .v2ray.core.common.protocol.User user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.v2ray.core.common.protocol.UserProto.User, com.v2ray.core.common.protocol.UserProto.User.Builder, com.v2ray.core.common.protocol.UserProto.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.v2ray.core.common.protocol.UserProto.User, com.v2ray.core.common.protocol.UserProto.User.Builder, com.v2ray.core.common.protocol.UserProto.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:v2ray.core.proxy.shadowsocks.ServerConfig)
    }

    // @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.ServerConfig)
    private static final com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig();
    }

    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerConfig>
        PARSER = new com.google.protobuf.AbstractParser<ServerConfig>() {
      public ServerConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerConfig> getParserForType() {
      return PARSER;
    }

    public com.v2ray.core.proxy.shadowsocks.ConfigProto.ServerConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.shadowsocks.ClientConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    java.util.List<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint> 
        getServerList();
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint getServer(int index);
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    int getServerCount();
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    java.util.List<? extends com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder> 
        getServerOrBuilderList();
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder getServerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code v2ray.core.proxy.shadowsocks.ClientConfig}
   */
  public  static final class ClientConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v2ray.core.proxy.shadowsocks.ClientConfig)
      ClientConfigOrBuilder {
    // Use ClientConfig.newBuilder() to construct.
    private ClientConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientConfig() {
      server_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                server_ = new java.util.ArrayList<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint>();
                mutable_bitField0_ |= 0x00000001;
              }
              server_.add(
                  input.readMessage(com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          server_ = java.util.Collections.unmodifiableList(server_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig.class, com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig.Builder.class);
    }

    public static final int SERVER_FIELD_NUMBER = 1;
    private java.util.List<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint> server_;
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public java.util.List<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint> getServerList() {
      return server_;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public java.util.List<? extends com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder> 
        getServerOrBuilderList() {
      return server_;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public int getServerCount() {
      return server_.size();
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint getServer(int index) {
      return server_.get(index);
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder getServerOrBuilder(
        int index) {
      return server_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < server_.size(); i++) {
        output.writeMessage(1, server_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < server_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, server_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig)) {
        return super.equals(obj);
      }
      com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig other = (com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig) obj;

      boolean result = true;
      result = result && getServerList()
          .equals(other.getServerList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getServerCount() > 0) {
        hash = (37 * hash) + SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getServerList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v2ray.core.proxy.shadowsocks.ClientConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v2ray.core.proxy.shadowsocks.ClientConfig)
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig.class, com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig.Builder.class);
      }

      // Construct using com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getServerFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (serverBuilder_ == null) {
          server_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          serverBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_descriptor;
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig getDefaultInstanceForType() {
        return com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig.getDefaultInstance();
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig build() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig buildPartial() {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig result = new com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig(this);
        int from_bitField0_ = bitField0_;
        if (serverBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            server_ = java.util.Collections.unmodifiableList(server_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.server_ = server_;
        } else {
          result.server_ = serverBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig) {
          return mergeFrom((com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig other) {
        if (other == com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig.getDefaultInstance()) return this;
        if (serverBuilder_ == null) {
          if (!other.server_.isEmpty()) {
            if (server_.isEmpty()) {
              server_ = other.server_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureServerIsMutable();
              server_.addAll(other.server_);
            }
            onChanged();
          }
        } else {
          if (!other.server_.isEmpty()) {
            if (serverBuilder_.isEmpty()) {
              serverBuilder_.dispose();
              serverBuilder_ = null;
              server_ = other.server_;
              bitField0_ = (bitField0_ & ~0x00000001);
              serverBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getServerFieldBuilder() : null;
            } else {
              serverBuilder_.addAllMessages(other.server_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint> server_ =
        java.util.Collections.emptyList();
      private void ensureServerIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          server_ = new java.util.ArrayList<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint>(server_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder> serverBuilder_;

      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public java.util.List<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint> getServerList() {
        if (serverBuilder_ == null) {
          return java.util.Collections.unmodifiableList(server_);
        } else {
          return serverBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public int getServerCount() {
        if (serverBuilder_ == null) {
          return server_.size();
        } else {
          return serverBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint getServer(int index) {
        if (serverBuilder_ == null) {
          return server_.get(index);
        } else {
          return serverBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder setServer(
          int index, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint value) {
        if (serverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerIsMutable();
          server_.set(index, value);
          onChanged();
        } else {
          serverBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder setServer(
          int index, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder builderForValue) {
        if (serverBuilder_ == null) {
          ensureServerIsMutable();
          server_.set(index, builderForValue.build());
          onChanged();
        } else {
          serverBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder addServer(com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint value) {
        if (serverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerIsMutable();
          server_.add(value);
          onChanged();
        } else {
          serverBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder addServer(
          int index, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint value) {
        if (serverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerIsMutable();
          server_.add(index, value);
          onChanged();
        } else {
          serverBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder addServer(
          com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder builderForValue) {
        if (serverBuilder_ == null) {
          ensureServerIsMutable();
          server_.add(builderForValue.build());
          onChanged();
        } else {
          serverBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder addServer(
          int index, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder builderForValue) {
        if (serverBuilder_ == null) {
          ensureServerIsMutable();
          server_.add(index, builderForValue.build());
          onChanged();
        } else {
          serverBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder addAllServer(
          java.lang.Iterable<? extends com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint> values) {
        if (serverBuilder_ == null) {
          ensureServerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, server_);
          onChanged();
        } else {
          serverBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder clearServer() {
        if (serverBuilder_ == null) {
          server_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          serverBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public Builder removeServer(int index) {
        if (serverBuilder_ == null) {
          ensureServerIsMutable();
          server_.remove(index);
          onChanged();
        } else {
          serverBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder getServerBuilder(
          int index) {
        return getServerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder getServerOrBuilder(
          int index) {
        if (serverBuilder_ == null) {
          return server_.get(index);  } else {
          return serverBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public java.util.List<? extends com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder> 
           getServerOrBuilderList() {
        if (serverBuilder_ != null) {
          return serverBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(server_);
        }
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder addServerBuilder() {
        return getServerFieldBuilder().addBuilder(
            com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder addServerBuilder(
          int index) {
        return getServerFieldBuilder().addBuilder(
            index, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
       */
      public java.util.List<com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder> 
           getServerBuilderList() {
        return getServerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder> 
          getServerFieldBuilder() {
        if (serverBuilder_ == null) {
          serverBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpoint.Builder, com.v2ray.core.common.protocol.ServerSpecProto.ServerEndpointOrBuilder>(
                  server_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          server_ = null;
        }
        return serverBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:v2ray.core.proxy.shadowsocks.ClientConfig)
    }

    // @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.ClientConfig)
    private static final com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig();
    }

    public static com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientConfig>
        PARSER = new com.google.protobuf.AbstractParser<ClientConfig>() {
      public ClientConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientConfig> getParserForType() {
      return PARSER;
    }

    public com.v2ray.core.proxy.shadowsocks.ConfigProto.ClientConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_proxy_shadowsocks_Account_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_proxy_shadowsocks_Account_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-v2ray.com/core/proxy/shadowsocks/confi" +
      "g.proto\022\034v2ray.core.proxy.shadowsocks\032)v" +
      "2ray.com/core/common/protocol/user.proto" +
      "\0320v2ray.com/core/common/protocol/server_" +
      "spec.proto\"\316\001\n\007Account\022\020\n\010password\030\001 \001(\t" +
      "\022=\n\013cipher_type\030\002 \001(\0162(.v2ray.core.proxy" +
      ".shadowsocks.CipherType\022>\n\003ota\030\003 \001(\01621.v" +
      "2ray.core.proxy.shadowsocks.Account.OneT" +
      "imeAuth\"2\n\013OneTimeAuth\022\010\n\004Auto\020\000\022\014\n\010Disa" +
      "bled\020\001\022\013\n\007Enabled\020\002\"S\n\014ServerConfig\022\023\n\013u",
      "dp_enabled\030\001 \001(\010\022.\n\004user\030\002 \001(\0132 .v2ray.c" +
      "ore.common.protocol.User\"J\n\014ClientConfig" +
      "\022:\n\006server\030\001 \003(\0132*.v2ray.core.common.pro" +
      "tocol.ServerEndpoint*\\\n\nCipherType\022\013\n\007UN" +
      "KNOWN\020\000\022\017\n\013AES_128_CFB\020\001\022\017\n\013AES_256_CFB\020" +
      "\002\022\014\n\010CHACHA20\020\003\022\021\n\rCHACHA20_IETF\020\004B[\n co" +
      "m.v2ray.core.proxy.shadowsocksB\013ConfigPr" +
      "otoZ\013shadowsocks\252\002\034V2Ray.Core.Proxy.Shad" +
      "owsocksb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.v2ray.core.common.protocol.UserProto.getDescriptor(),
          com.v2ray.core.common.protocol.ServerSpecProto.getDescriptor(),
        }, assigner);
    internal_static_v2ray_core_proxy_shadowsocks_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_proxy_shadowsocks_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_proxy_shadowsocks_Account_descriptor,
        new java.lang.String[] { "Password", "CipherType", "Ota", });
    internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor,
        new java.lang.String[] { "UdpEnabled", "User", });
    internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_proxy_shadowsocks_ClientConfig_descriptor,
        new java.lang.String[] { "Server", });
    com.v2ray.core.common.protocol.UserProto.getDescriptor();
    com.v2ray.core.common.protocol.ServerSpecProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
