// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/proxy/http/config.proto

package com.v2ray.core.proxy.http;

public interface ServerConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.http.ServerConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 timeout = 1;</code>
   */
  int getTimeout();
}
