// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/transport/internet/websocket/config.proto

package com.v2ray.core.transport.internet.websocket;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_transport_internet_websocket_ConnectionReuse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_transport_internet_websocket_ConnectionReuse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_transport_internet_websocket_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_transport_internet_websocket_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8v2ray.com/core/transport/internet/webs" +
      "ocket/config.proto\022\'v2ray.core.transport" +
      ".internet.websocket\"!\n\017ConnectionReuse\022\016" +
      "\n\006enable\030\001 \001(\010\"j\n\006Config\022R\n\020connection_r" +
      "euse\030\001 \001(\01328.v2ray.core.transport.intern" +
      "et.websocket.ConnectionReuse\022\014\n\004path\030\002 \001" +
      "(\tBd\n+com.v2ray.core.transport.internet." +
      "websocketP\001Z\twebsocket\252\002\'V2Ray.Core.Tran" +
      "sport.Internet.Websocketb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_v2ray_core_transport_internet_websocket_ConnectionReuse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_transport_internet_websocket_ConnectionReuse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_transport_internet_websocket_ConnectionReuse_descriptor,
        new java.lang.String[] { "Enable", });
    internal_static_v2ray_core_transport_internet_websocket_Config_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v2ray_core_transport_internet_websocket_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_transport_internet_websocket_Config_descriptor,
        new java.lang.String[] { "ConnectionReuse", "Path", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
