// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/common/protocol/headers.proto

package com.v2ray.core.common.protocol;

public final class HeadersProto {
  private HeadersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code v2ray.core.common.protocol.SecurityType}
   */
  public enum SecurityType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>LEGACY = 1;</code>
     */
    LEGACY(1),
    /**
     * <code>AUTO = 2;</code>
     */
    AUTO(2),
    /**
     * <code>AES128_GCM = 3;</code>
     */
    AES128_GCM(3),
    /**
     * <code>CHACHA20_POLY1305 = 4;</code>
     */
    CHACHA20_POLY1305(4),
    /**
     * <code>NONE = 5;</code>
     */
    NONE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>LEGACY = 1;</code>
     */
    public static final int LEGACY_VALUE = 1;
    /**
     * <code>AUTO = 2;</code>
     */
    public static final int AUTO_VALUE = 2;
    /**
     * <code>AES128_GCM = 3;</code>
     */
    public static final int AES128_GCM_VALUE = 3;
    /**
     * <code>CHACHA20_POLY1305 = 4;</code>
     */
    public static final int CHACHA20_POLY1305_VALUE = 4;
    /**
     * <code>NONE = 5;</code>
     */
    public static final int NONE_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SecurityType valueOf(int value) {
      return forNumber(value);
    }

    public static SecurityType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return LEGACY;
        case 2: return AUTO;
        case 3: return AES128_GCM;
        case 4: return CHACHA20_POLY1305;
        case 5: return NONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SecurityType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SecurityType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SecurityType>() {
            public SecurityType findValueByNumber(int number) {
              return SecurityType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.v2ray.core.common.protocol.HeadersProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final SecurityType[] VALUES = values();

    public static SecurityType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SecurityType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:v2ray.core.common.protocol.SecurityType)
  }

  public interface SecurityConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v2ray.core.common.protocol.SecurityConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
     */
    com.v2ray.core.common.protocol.HeadersProto.SecurityType getType();
  }
  /**
   * Protobuf type {@code v2ray.core.common.protocol.SecurityConfig}
   */
  public  static final class SecurityConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v2ray.core.common.protocol.SecurityConfig)
      SecurityConfigOrBuilder {
    // Use SecurityConfig.newBuilder() to construct.
    private SecurityConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SecurityConfig() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SecurityConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.common.protocol.HeadersProto.internal_static_v2ray_core_common_protocol_SecurityConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.common.protocol.HeadersProto.internal_static_v2ray_core_common_protocol_SecurityConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.common.protocol.HeadersProto.SecurityConfig.class, com.v2ray.core.common.protocol.HeadersProto.SecurityConfig.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
     */
    public com.v2ray.core.common.protocol.HeadersProto.SecurityType getType() {
      com.v2ray.core.common.protocol.HeadersProto.SecurityType result = com.v2ray.core.common.protocol.HeadersProto.SecurityType.valueOf(type_);
      return result == null ? com.v2ray.core.common.protocol.HeadersProto.SecurityType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.v2ray.core.common.protocol.HeadersProto.SecurityType.UNKNOWN.getNumber()) {
        output.writeEnum(1, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.v2ray.core.common.protocol.HeadersProto.SecurityType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.v2ray.core.common.protocol.HeadersProto.SecurityConfig)) {
        return super.equals(obj);
      }
      com.v2ray.core.common.protocol.HeadersProto.SecurityConfig other = (com.v2ray.core.common.protocol.HeadersProto.SecurityConfig) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.v2ray.core.common.protocol.HeadersProto.SecurityConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v2ray.core.common.protocol.SecurityConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v2ray.core.common.protocol.SecurityConfig)
        com.v2ray.core.common.protocol.HeadersProto.SecurityConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.v2ray.core.common.protocol.HeadersProto.internal_static_v2ray_core_common_protocol_SecurityConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.v2ray.core.common.protocol.HeadersProto.internal_static_v2ray_core_common_protocol_SecurityConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.v2ray.core.common.protocol.HeadersProto.SecurityConfig.class, com.v2ray.core.common.protocol.HeadersProto.SecurityConfig.Builder.class);
      }

      // Construct using com.v2ray.core.common.protocol.HeadersProto.SecurityConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.v2ray.core.common.protocol.HeadersProto.internal_static_v2ray_core_common_protocol_SecurityConfig_descriptor;
      }

      public com.v2ray.core.common.protocol.HeadersProto.SecurityConfig getDefaultInstanceForType() {
        return com.v2ray.core.common.protocol.HeadersProto.SecurityConfig.getDefaultInstance();
      }

      public com.v2ray.core.common.protocol.HeadersProto.SecurityConfig build() {
        com.v2ray.core.common.protocol.HeadersProto.SecurityConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.v2ray.core.common.protocol.HeadersProto.SecurityConfig buildPartial() {
        com.v2ray.core.common.protocol.HeadersProto.SecurityConfig result = new com.v2ray.core.common.protocol.HeadersProto.SecurityConfig(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.v2ray.core.common.protocol.HeadersProto.SecurityConfig) {
          return mergeFrom((com.v2ray.core.common.protocol.HeadersProto.SecurityConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.v2ray.core.common.protocol.HeadersProto.SecurityConfig other) {
        if (other == com.v2ray.core.common.protocol.HeadersProto.SecurityConfig.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.v2ray.core.common.protocol.HeadersProto.SecurityConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.v2ray.core.common.protocol.HeadersProto.SecurityConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
       */
      public com.v2ray.core.common.protocol.HeadersProto.SecurityType getType() {
        com.v2ray.core.common.protocol.HeadersProto.SecurityType result = com.v2ray.core.common.protocol.HeadersProto.SecurityType.valueOf(type_);
        return result == null ? com.v2ray.core.common.protocol.HeadersProto.SecurityType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
       */
      public Builder setType(com.v2ray.core.common.protocol.HeadersProto.SecurityType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .v2ray.core.common.protocol.SecurityType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:v2ray.core.common.protocol.SecurityConfig)
    }

    // @@protoc_insertion_point(class_scope:v2ray.core.common.protocol.SecurityConfig)
    private static final com.v2ray.core.common.protocol.HeadersProto.SecurityConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.v2ray.core.common.protocol.HeadersProto.SecurityConfig();
    }

    public static com.v2ray.core.common.protocol.HeadersProto.SecurityConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SecurityConfig>
        PARSER = new com.google.protobuf.AbstractParser<SecurityConfig>() {
      public SecurityConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SecurityConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SecurityConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SecurityConfig> getParserForType() {
      return PARSER;
    }

    public com.v2ray.core.common.protocol.HeadersProto.SecurityConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_common_protocol_SecurityConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_common_protocol_SecurityConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,v2ray.com/core/common/protocol/headers" +
      ".proto\022\032v2ray.core.common.protocol\"H\n\016Se" +
      "curityConfig\0226\n\004type\030\001 \001(\0162(.v2ray.core." +
      "common.protocol.SecurityType*b\n\014Security" +
      "Type\022\013\n\007UNKNOWN\020\000\022\n\n\006LEGACY\020\001\022\010\n\004AUTO\020\002\022" +
      "\016\n\nAES128_GCM\020\003\022\025\n\021CHACHA20_POLY1305\020\004\022\010" +
      "\n\004NONE\020\005BU\n\036com.v2ray.core.common.protoc" +
      "olB\014HeadersProtoZ\010protocol\252\002\032V2Ray.Core." +
      "Common.Protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_v2ray_core_common_protocol_SecurityConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_common_protocol_SecurityConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_common_protocol_SecurityConfig_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
