// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/proxy/dokodemo/config.proto

package com.v2ray.core.proxy.dokodemo;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.dokodemo.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .v2ray.core.common.net.IPOrDomain address = 1;</code>
   */
  boolean hasAddress();
  /**
   * <code>optional .v2ray.core.common.net.IPOrDomain address = 1;</code>
   */
  com.v2ray.core.common.net.IPOrDomain getAddress();
  /**
   * <code>optional .v2ray.core.common.net.IPOrDomain address = 1;</code>
   */
  com.v2ray.core.common.net.IPOrDomainOrBuilder getAddressOrBuilder();

  /**
   * <code>optional uint32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>optional .v2ray.core.common.net.NetworkList network_list = 3;</code>
   */
  boolean hasNetworkList();
  /**
   * <code>optional .v2ray.core.common.net.NetworkList network_list = 3;</code>
   */
  com.v2ray.core.common.net.NetworkList getNetworkList();
  /**
   * <code>optional .v2ray.core.common.net.NetworkList network_list = 3;</code>
   */
  com.v2ray.core.common.net.NetworkListOrBuilder getNetworkListOrBuilder();

  /**
   * <code>optional uint32 timeout = 4;</code>
   */
  int getTimeout();

  /**
   * <code>optional bool follow_redirect = 5;</code>
   */
  boolean getFollowRedirect();
}
