// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/proxyman/config.proto

package com.v2ray.core.app.proxyman;

public interface InboundHandlerConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.proxyman.InboundHandlerConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage receiver_settings = 2;</code>
   */
  boolean hasReceiverSettings();
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage receiver_settings = 2;</code>
   */
  com.v2ray.core.common.serial.TypedMessage getReceiverSettings();
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage receiver_settings = 2;</code>
   */
  com.v2ray.core.common.serial.TypedMessageOrBuilder getReceiverSettingsOrBuilder();

  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
   */
  boolean hasProxySettings();
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
   */
  com.v2ray.core.common.serial.TypedMessage getProxySettings();
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
   */
  com.v2ray.core.common.serial.TypedMessageOrBuilder getProxySettingsOrBuilder();
}
