// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/proxyman/config.proto

package com.v2ray.core.app.proxyman;

/**
 * Protobuf type {@code v2ray.core.app.proxyman.OutboundHandlerConfig}
 */
public  final class OutboundHandlerConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.proxyman.OutboundHandlerConfig)
    OutboundHandlerConfigOrBuilder {
  // Use OutboundHandlerConfig.newBuilder() to construct.
  private OutboundHandlerConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutboundHandlerConfig() {
    tag_ = "";
    expire_ = 0L;
    comment_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OutboundHandlerConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tag_ = s;
            break;
          }
          case 18: {
            com.v2ray.core.common.serial.TypedMessage.Builder subBuilder = null;
            if (senderSettings_ != null) {
              subBuilder = senderSettings_.toBuilder();
            }
            senderSettings_ = input.readMessage(com.v2ray.core.common.serial.TypedMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(senderSettings_);
              senderSettings_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.v2ray.core.common.serial.TypedMessage.Builder subBuilder = null;
            if (proxySettings_ != null) {
              subBuilder = proxySettings_.toBuilder();
            }
            proxySettings_ = input.readMessage(com.v2ray.core.common.serial.TypedMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(proxySettings_);
              proxySettings_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            expire_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            comment_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.proxyman.Config.internal_static_v2ray_core_app_proxyman_OutboundHandlerConfig_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.proxyman.Config.internal_static_v2ray_core_app_proxyman_OutboundHandlerConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.proxyman.OutboundHandlerConfig.class, com.v2ray.core.app.proxyman.OutboundHandlerConfig.Builder.class);
  }

  public static final int TAG_FIELD_NUMBER = 1;
  private volatile java.lang.Object tag_;
  /**
   * <code>optional string tag = 1;</code>
   */
  public java.lang.String getTag() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tag_ = s;
      return s;
    }
  }
  /**
   * <code>optional string tag = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTagBytes() {
    java.lang.Object ref = tag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_SETTINGS_FIELD_NUMBER = 2;
  private com.v2ray.core.common.serial.TypedMessage senderSettings_;
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
   */
  public boolean hasSenderSettings() {
    return senderSettings_ != null;
  }
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
   */
  public com.v2ray.core.common.serial.TypedMessage getSenderSettings() {
    return senderSettings_ == null ? com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : senderSettings_;
  }
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
   */
  public com.v2ray.core.common.serial.TypedMessageOrBuilder getSenderSettingsOrBuilder() {
    return getSenderSettings();
  }

  public static final int PROXY_SETTINGS_FIELD_NUMBER = 3;
  private com.v2ray.core.common.serial.TypedMessage proxySettings_;
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
   */
  public boolean hasProxySettings() {
    return proxySettings_ != null;
  }
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
   */
  public com.v2ray.core.common.serial.TypedMessage getProxySettings() {
    return proxySettings_ == null ? com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : proxySettings_;
  }
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
   */
  public com.v2ray.core.common.serial.TypedMessageOrBuilder getProxySettingsOrBuilder() {
    return getProxySettings();
  }

  public static final int EXPIRE_FIELD_NUMBER = 4;
  private long expire_;
  /**
   * <code>optional int64 expire = 4;</code>
   */
  public long getExpire() {
    return expire_;
  }

  public static final int COMMENT_FIELD_NUMBER = 5;
  private volatile java.lang.Object comment_;
  /**
   * <code>optional string comment = 5;</code>
   */
  public java.lang.String getComment() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comment_ = s;
      return s;
    }
  }
  /**
   * <code>optional string comment = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCommentBytes() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTagBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tag_);
    }
    if (senderSettings_ != null) {
      output.writeMessage(2, getSenderSettings());
    }
    if (proxySettings_ != null) {
      output.writeMessage(3, getProxySettings());
    }
    if (expire_ != 0L) {
      output.writeInt64(4, expire_);
    }
    if (!getCommentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, comment_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTagBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tag_);
    }
    if (senderSettings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSenderSettings());
    }
    if (proxySettings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getProxySettings());
    }
    if (expire_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, expire_);
    }
    if (!getCommentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, comment_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.proxyman.OutboundHandlerConfig)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.proxyman.OutboundHandlerConfig other = (com.v2ray.core.app.proxyman.OutboundHandlerConfig) obj;

    boolean result = true;
    result = result && getTag()
        .equals(other.getTag());
    result = result && (hasSenderSettings() == other.hasSenderSettings());
    if (hasSenderSettings()) {
      result = result && getSenderSettings()
          .equals(other.getSenderSettings());
    }
    result = result && (hasProxySettings() == other.hasProxySettings());
    if (hasProxySettings()) {
      result = result && getProxySettings()
          .equals(other.getProxySettings());
    }
    result = result && (getExpire()
        == other.getExpire());
    result = result && getComment()
        .equals(other.getComment());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TAG_FIELD_NUMBER;
    hash = (53 * hash) + getTag().hashCode();
    if (hasSenderSettings()) {
      hash = (37 * hash) + SENDER_SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getSenderSettings().hashCode();
    }
    if (hasProxySettings()) {
      hash = (37 * hash) + PROXY_SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getProxySettings().hashCode();
    }
    hash = (37 * hash) + EXPIRE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpire());
    hash = (37 * hash) + COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getComment().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.proxyman.OutboundHandlerConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.app.proxyman.OutboundHandlerConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.proxyman.OutboundHandlerConfig)
      com.v2ray.core.app.proxyman.OutboundHandlerConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.proxyman.Config.internal_static_v2ray_core_app_proxyman_OutboundHandlerConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.proxyman.Config.internal_static_v2ray_core_app_proxyman_OutboundHandlerConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.proxyman.OutboundHandlerConfig.class, com.v2ray.core.app.proxyman.OutboundHandlerConfig.Builder.class);
    }

    // Construct using com.v2ray.core.app.proxyman.OutboundHandlerConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      tag_ = "";

      if (senderSettingsBuilder_ == null) {
        senderSettings_ = null;
      } else {
        senderSettings_ = null;
        senderSettingsBuilder_ = null;
      }
      if (proxySettingsBuilder_ == null) {
        proxySettings_ = null;
      } else {
        proxySettings_ = null;
        proxySettingsBuilder_ = null;
      }
      expire_ = 0L;

      comment_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.proxyman.Config.internal_static_v2ray_core_app_proxyman_OutboundHandlerConfig_descriptor;
    }

    public com.v2ray.core.app.proxyman.OutboundHandlerConfig getDefaultInstanceForType() {
      return com.v2ray.core.app.proxyman.OutboundHandlerConfig.getDefaultInstance();
    }

    public com.v2ray.core.app.proxyman.OutboundHandlerConfig build() {
      com.v2ray.core.app.proxyman.OutboundHandlerConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.v2ray.core.app.proxyman.OutboundHandlerConfig buildPartial() {
      com.v2ray.core.app.proxyman.OutboundHandlerConfig result = new com.v2ray.core.app.proxyman.OutboundHandlerConfig(this);
      result.tag_ = tag_;
      if (senderSettingsBuilder_ == null) {
        result.senderSettings_ = senderSettings_;
      } else {
        result.senderSettings_ = senderSettingsBuilder_.build();
      }
      if (proxySettingsBuilder_ == null) {
        result.proxySettings_ = proxySettings_;
      } else {
        result.proxySettings_ = proxySettingsBuilder_.build();
      }
      result.expire_ = expire_;
      result.comment_ = comment_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.proxyman.OutboundHandlerConfig) {
        return mergeFrom((com.v2ray.core.app.proxyman.OutboundHandlerConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.proxyman.OutboundHandlerConfig other) {
      if (other == com.v2ray.core.app.proxyman.OutboundHandlerConfig.getDefaultInstance()) return this;
      if (!other.getTag().isEmpty()) {
        tag_ = other.tag_;
        onChanged();
      }
      if (other.hasSenderSettings()) {
        mergeSenderSettings(other.getSenderSettings());
      }
      if (other.hasProxySettings()) {
        mergeProxySettings(other.getProxySettings());
      }
      if (other.getExpire() != 0L) {
        setExpire(other.getExpire());
      }
      if (!other.getComment().isEmpty()) {
        comment_ = other.comment_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.v2ray.core.app.proxyman.OutboundHandlerConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.v2ray.core.app.proxyman.OutboundHandlerConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object tag_ = "";
    /**
     * <code>optional string tag = 1;</code>
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string tag = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tag = 1;</code>
     */
    public Builder setTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tag = 1;</code>
     */
    public Builder clearTag() {
      
      tag_ = getDefaultInstance().getTag();
      onChanged();
      return this;
    }
    /**
     * <code>optional string tag = 1;</code>
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tag_ = value;
      onChanged();
      return this;
    }

    private com.v2ray.core.common.serial.TypedMessage senderSettings_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder> senderSettingsBuilder_;
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public boolean hasSenderSettings() {
      return senderSettingsBuilder_ != null || senderSettings_ != null;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public com.v2ray.core.common.serial.TypedMessage getSenderSettings() {
      if (senderSettingsBuilder_ == null) {
        return senderSettings_ == null ? com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : senderSettings_;
      } else {
        return senderSettingsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public Builder setSenderSettings(com.v2ray.core.common.serial.TypedMessage value) {
      if (senderSettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        senderSettings_ = value;
        onChanged();
      } else {
        senderSettingsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public Builder setSenderSettings(
        com.v2ray.core.common.serial.TypedMessage.Builder builderForValue) {
      if (senderSettingsBuilder_ == null) {
        senderSettings_ = builderForValue.build();
        onChanged();
      } else {
        senderSettingsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public Builder mergeSenderSettings(com.v2ray.core.common.serial.TypedMessage value) {
      if (senderSettingsBuilder_ == null) {
        if (senderSettings_ != null) {
          senderSettings_ =
            com.v2ray.core.common.serial.TypedMessage.newBuilder(senderSettings_).mergeFrom(value).buildPartial();
        } else {
          senderSettings_ = value;
        }
        onChanged();
      } else {
        senderSettingsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public Builder clearSenderSettings() {
      if (senderSettingsBuilder_ == null) {
        senderSettings_ = null;
        onChanged();
      } else {
        senderSettings_ = null;
        senderSettingsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public com.v2ray.core.common.serial.TypedMessage.Builder getSenderSettingsBuilder() {
      
      onChanged();
      return getSenderSettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    public com.v2ray.core.common.serial.TypedMessageOrBuilder getSenderSettingsOrBuilder() {
      if (senderSettingsBuilder_ != null) {
        return senderSettingsBuilder_.getMessageOrBuilder();
      } else {
        return senderSettings_ == null ?
            com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : senderSettings_;
      }
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage sender_settings = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder> 
        getSenderSettingsFieldBuilder() {
      if (senderSettingsBuilder_ == null) {
        senderSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder>(
                getSenderSettings(),
                getParentForChildren(),
                isClean());
        senderSettings_ = null;
      }
      return senderSettingsBuilder_;
    }

    private com.v2ray.core.common.serial.TypedMessage proxySettings_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder> proxySettingsBuilder_;
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public boolean hasProxySettings() {
      return proxySettingsBuilder_ != null || proxySettings_ != null;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public com.v2ray.core.common.serial.TypedMessage getProxySettings() {
      if (proxySettingsBuilder_ == null) {
        return proxySettings_ == null ? com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : proxySettings_;
      } else {
        return proxySettingsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public Builder setProxySettings(com.v2ray.core.common.serial.TypedMessage value) {
      if (proxySettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        proxySettings_ = value;
        onChanged();
      } else {
        proxySettingsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public Builder setProxySettings(
        com.v2ray.core.common.serial.TypedMessage.Builder builderForValue) {
      if (proxySettingsBuilder_ == null) {
        proxySettings_ = builderForValue.build();
        onChanged();
      } else {
        proxySettingsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public Builder mergeProxySettings(com.v2ray.core.common.serial.TypedMessage value) {
      if (proxySettingsBuilder_ == null) {
        if (proxySettings_ != null) {
          proxySettings_ =
            com.v2ray.core.common.serial.TypedMessage.newBuilder(proxySettings_).mergeFrom(value).buildPartial();
        } else {
          proxySettings_ = value;
        }
        onChanged();
      } else {
        proxySettingsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public Builder clearProxySettings() {
      if (proxySettingsBuilder_ == null) {
        proxySettings_ = null;
        onChanged();
      } else {
        proxySettings_ = null;
        proxySettingsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public com.v2ray.core.common.serial.TypedMessage.Builder getProxySettingsBuilder() {
      
      onChanged();
      return getProxySettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    public com.v2ray.core.common.serial.TypedMessageOrBuilder getProxySettingsOrBuilder() {
      if (proxySettingsBuilder_ != null) {
        return proxySettingsBuilder_.getMessageOrBuilder();
      } else {
        return proxySettings_ == null ?
            com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : proxySettings_;
      }
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage proxy_settings = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder> 
        getProxySettingsFieldBuilder() {
      if (proxySettingsBuilder_ == null) {
        proxySettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder>(
                getProxySettings(),
                getParentForChildren(),
                isClean());
        proxySettings_ = null;
      }
      return proxySettingsBuilder_;
    }

    private long expire_ ;
    /**
     * <code>optional int64 expire = 4;</code>
     */
    public long getExpire() {
      return expire_;
    }
    /**
     * <code>optional int64 expire = 4;</code>
     */
    public Builder setExpire(long value) {
      
      expire_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 expire = 4;</code>
     */
    public Builder clearExpire() {
      
      expire_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object comment_ = "";
    /**
     * <code>optional string comment = 5;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string comment = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string comment = 5;</code>
     */
    public Builder setComment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      comment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string comment = 5;</code>
     */
    public Builder clearComment() {
      
      comment_ = getDefaultInstance().getComment();
      onChanged();
      return this;
    }
    /**
     * <code>optional string comment = 5;</code>
     */
    public Builder setCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      comment_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.proxyman.OutboundHandlerConfig)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.proxyman.OutboundHandlerConfig)
  private static final com.v2ray.core.app.proxyman.OutboundHandlerConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.proxyman.OutboundHandlerConfig();
  }

  public static com.v2ray.core.app.proxyman.OutboundHandlerConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutboundHandlerConfig>
      PARSER = new com.google.protobuf.AbstractParser<OutboundHandlerConfig>() {
    public OutboundHandlerConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OutboundHandlerConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OutboundHandlerConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutboundHandlerConfig> getParserForType() {
    return PARSER;
  }

  public com.v2ray.core.app.proxyman.OutboundHandlerConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

