// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/proxyman/config.proto

package com.v2ray.core.app.proxyman;

public interface SessionFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.proxyman.SessionFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional .v2ray.core.common.net.Endpoint target = 2;</code>
   */
  boolean hasTarget();
  /**
   * <code>optional .v2ray.core.common.net.Endpoint target = 2;</code>
   */
  com.v2ray.core.common.net.Endpoint getTarget();
  /**
   * <code>optional .v2ray.core.common.net.Endpoint target = 2;</code>
   */
  com.v2ray.core.common.net.EndpointOrBuilder getTargetOrBuilder();

  /**
   * <code>optional bytes payload = 3;</code>
   */
  com.google.protobuf.ByteString getPayload();
}
