// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/common/net/network.proto

package com.v2ray.core.common.net;

public final class NetworkProto {
  private NetworkProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code v2ray.core.common.net.Network}
   */
  public enum Network
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <pre>
     * Native TCP provided by system.
     * </pre>
     *
     * <code>RawTCP = 1 [deprecated = true];</code>
     */
    @java.lang.Deprecated
    RawTCP(1),
    /**
     * <pre>
     * V2Ray specific TCP.
     * </pre>
     *
     * <code>TCP = 2;</code>
     */
    TCP(2),
    /**
     * <code>UDP = 3;</code>
     */
    UDP(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <pre>
     * Native TCP provided by system.
     * </pre>
     *
     * <code>RawTCP = 1 [deprecated = true];</code>
     */
    public static final int RawTCP_VALUE = 1;
    /**
     * <pre>
     * V2Ray specific TCP.
     * </pre>
     *
     * <code>TCP = 2;</code>
     */
    public static final int TCP_VALUE = 2;
    /**
     * <code>UDP = 3;</code>
     */
    public static final int UDP_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Network valueOf(int value) {
      return forNumber(value);
    }

    public static Network forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return RawTCP;
        case 2: return TCP;
        case 3: return UDP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Network>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Network> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Network>() {
            public Network findValueByNumber(int number) {
              return Network.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.v2ray.core.common.net.NetworkProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Network[] VALUES = values();

    public static Network valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Network(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:v2ray.core.common.net.Network)
  }

  public interface NetworkListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v2ray.core.common.net.NetworkList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    java.util.List<com.v2ray.core.common.net.NetworkProto.Network> getNetworkList();
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    int getNetworkCount();
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    com.v2ray.core.common.net.NetworkProto.Network getNetwork(int index);
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    java.util.List<java.lang.Integer>
    getNetworkValueList();
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    int getNetworkValue(int index);
  }
  /**
   * Protobuf type {@code v2ray.core.common.net.NetworkList}
   */
  public  static final class NetworkList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v2ray.core.common.net.NetworkList)
      NetworkListOrBuilder {
    // Use NetworkList.newBuilder() to construct.
    private NetworkList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkList() {
      network_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NetworkList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                network_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              network_.add(rawValue);
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  network_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                network_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          network_ = java.util.Collections.unmodifiableList(network_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.common.net.NetworkProto.internal_static_v2ray_core_common_net_NetworkList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.common.net.NetworkProto.internal_static_v2ray_core_common_net_NetworkList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.common.net.NetworkProto.NetworkList.class, com.v2ray.core.common.net.NetworkProto.NetworkList.Builder.class);
    }

    public static final int NETWORK_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> network_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, com.v2ray.core.common.net.NetworkProto.Network> network_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, com.v2ray.core.common.net.NetworkProto.Network>() {
              public com.v2ray.core.common.net.NetworkProto.Network convert(java.lang.Integer from) {
                com.v2ray.core.common.net.NetworkProto.Network result = com.v2ray.core.common.net.NetworkProto.Network.valueOf(from);
                return result == null ? com.v2ray.core.common.net.NetworkProto.Network.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    public java.util.List<com.v2ray.core.common.net.NetworkProto.Network> getNetworkList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.v2ray.core.common.net.NetworkProto.Network>(network_, network_converter_);
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    public int getNetworkCount() {
      return network_.size();
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    public com.v2ray.core.common.net.NetworkProto.Network getNetwork(int index) {
      return network_converter_.convert(network_.get(index));
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    public java.util.List<java.lang.Integer>
    getNetworkValueList() {
      return network_;
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    public int getNetworkValue(int index) {
      return network_.get(index);
    }
    private int networkMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNetworkList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(networkMemoizedSerializedSize);
      }
      for (int i = 0; i < network_.size(); i++) {
        output.writeEnumNoTag(network_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < network_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(network_.get(i));
        }
        size += dataSize;
        if (!getNetworkList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }networkMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.v2ray.core.common.net.NetworkProto.NetworkList)) {
        return super.equals(obj);
      }
      com.v2ray.core.common.net.NetworkProto.NetworkList other = (com.v2ray.core.common.net.NetworkProto.NetworkList) obj;

      boolean result = true;
      result = result && network_.equals(other.network_);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getNetworkCount() > 0) {
        hash = (37 * hash) + NETWORK_FIELD_NUMBER;
        hash = (53 * hash) + network_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.v2ray.core.common.net.NetworkProto.NetworkList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.v2ray.core.common.net.NetworkProto.NetworkList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v2ray.core.common.net.NetworkList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v2ray.core.common.net.NetworkList)
        com.v2ray.core.common.net.NetworkProto.NetworkListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.v2ray.core.common.net.NetworkProto.internal_static_v2ray_core_common_net_NetworkList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.v2ray.core.common.net.NetworkProto.internal_static_v2ray_core_common_net_NetworkList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.v2ray.core.common.net.NetworkProto.NetworkList.class, com.v2ray.core.common.net.NetworkProto.NetworkList.Builder.class);
      }

      // Construct using com.v2ray.core.common.net.NetworkProto.NetworkList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        network_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.v2ray.core.common.net.NetworkProto.internal_static_v2ray_core_common_net_NetworkList_descriptor;
      }

      public com.v2ray.core.common.net.NetworkProto.NetworkList getDefaultInstanceForType() {
        return com.v2ray.core.common.net.NetworkProto.NetworkList.getDefaultInstance();
      }

      public com.v2ray.core.common.net.NetworkProto.NetworkList build() {
        com.v2ray.core.common.net.NetworkProto.NetworkList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.v2ray.core.common.net.NetworkProto.NetworkList buildPartial() {
        com.v2ray.core.common.net.NetworkProto.NetworkList result = new com.v2ray.core.common.net.NetworkProto.NetworkList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          network_ = java.util.Collections.unmodifiableList(network_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.network_ = network_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.v2ray.core.common.net.NetworkProto.NetworkList) {
          return mergeFrom((com.v2ray.core.common.net.NetworkProto.NetworkList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.v2ray.core.common.net.NetworkProto.NetworkList other) {
        if (other == com.v2ray.core.common.net.NetworkProto.NetworkList.getDefaultInstance()) return this;
        if (!other.network_.isEmpty()) {
          if (network_.isEmpty()) {
            network_ = other.network_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNetworkIsMutable();
            network_.addAll(other.network_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.v2ray.core.common.net.NetworkProto.NetworkList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.v2ray.core.common.net.NetworkProto.NetworkList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> network_ =
        java.util.Collections.emptyList();
      private void ensureNetworkIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          network_ = new java.util.ArrayList<java.lang.Integer>(network_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public java.util.List<com.v2ray.core.common.net.NetworkProto.Network> getNetworkList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, com.v2ray.core.common.net.NetworkProto.Network>(network_, network_converter_);
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public int getNetworkCount() {
        return network_.size();
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public com.v2ray.core.common.net.NetworkProto.Network getNetwork(int index) {
        return network_converter_.convert(network_.get(index));
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public Builder setNetwork(
          int index, com.v2ray.core.common.net.NetworkProto.Network value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNetworkIsMutable();
        network_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public Builder addNetwork(com.v2ray.core.common.net.NetworkProto.Network value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNetworkIsMutable();
        network_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public Builder addAllNetwork(
          java.lang.Iterable<? extends com.v2ray.core.common.net.NetworkProto.Network> values) {
        ensureNetworkIsMutable();
        for (com.v2ray.core.common.net.NetworkProto.Network value : values) {
          network_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public Builder clearNetwork() {
        network_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public java.util.List<java.lang.Integer>
      getNetworkValueList() {
        return java.util.Collections.unmodifiableList(network_);
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public int getNetworkValue(int index) {
        return network_.get(index);
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public Builder setNetworkValue(
          int index, int value) {
        ensureNetworkIsMutable();
        network_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public Builder addNetworkValue(int value) {
        ensureNetworkIsMutable();
        network_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
       */
      public Builder addAllNetworkValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureNetworkIsMutable();
        for (int value : values) {
          network_.add(value);
        }
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:v2ray.core.common.net.NetworkList)
    }

    // @@protoc_insertion_point(class_scope:v2ray.core.common.net.NetworkList)
    private static final com.v2ray.core.common.net.NetworkProto.NetworkList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.v2ray.core.common.net.NetworkProto.NetworkList();
    }

    public static com.v2ray.core.common.net.NetworkProto.NetworkList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetworkList>
        PARSER = new com.google.protobuf.AbstractParser<NetworkList>() {
      public NetworkList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NetworkList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetworkList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkList> getParserForType() {
      return PARSER;
    }

    public com.v2ray.core.common.net.NetworkProto.NetworkList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_common_net_NetworkList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_common_net_NetworkList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'v2ray.com/core/common/net/network.prot" +
      "o\022\025v2ray.core.common.net\">\n\013NetworkList\022" +
      "/\n\007network\030\001 \003(\0162\036.v2ray.core.common.net" +
      ".Network*8\n\007Network\022\013\n\007Unknown\020\000\022\016\n\006RawT" +
      "CP\020\001\032\002\010\001\022\007\n\003TCP\020\002\022\007\n\003UDP\020\003BF\n\031com.v2ray." +
      "core.common.netB\014NetworkProtoZ\003net\252\002\025V2R" +
      "ay.Core.Common.Netb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_v2ray_core_common_net_NetworkList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_common_net_NetworkList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_common_net_NetworkList_descriptor,
        new java.lang.String[] { "Network", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
