// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/web/config.proto

package com.v2ray.core.app.web;

public interface FileServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.web.FileServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .v2ray.core.app.web.FileServer.Entry entry = 1;</code>
   */
  java.util.List<com.v2ray.core.app.web.FileServer.Entry> 
      getEntryList();
  /**
   * <code>repeated .v2ray.core.app.web.FileServer.Entry entry = 1;</code>
   */
  com.v2ray.core.app.web.FileServer.Entry getEntry(int index);
  /**
   * <code>repeated .v2ray.core.app.web.FileServer.Entry entry = 1;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .v2ray.core.app.web.FileServer.Entry entry = 1;</code>
   */
  java.util.List<? extends com.v2ray.core.app.web.FileServer.EntryOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .v2ray.core.app.web.FileServer.Entry entry = 1;</code>
   */
  com.v2ray.core.app.web.FileServer.EntryOrBuilder getEntryOrBuilder(
      int index);
}
