// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/web/config.proto

package com.v2ray.core.app.web;

/**
 * Protobuf type {@code v2ray.core.app.web.Server}
 */
public  final class Server extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.web.Server)
    ServerOrBuilder {
  // Use Server.newBuilder() to construct.
  private Server(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Server() {
    domain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Server(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              domain_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            domain_.add(s);
            break;
          }
          case 18: {
            com.v2ray.core.common.serial.TypedMessage.Builder subBuilder = null;
            if (settings_ != null) {
              subBuilder = settings_.toBuilder();
            }
            settings_ = input.readMessage(com.v2ray.core.common.serial.TypedMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(settings_);
              settings_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        domain_ = domain_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.web.ConfigOuterClass.internal_static_v2ray_core_app_web_Server_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.web.ConfigOuterClass.internal_static_v2ray_core_app_web_Server_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.web.Server.class, com.v2ray.core.app.web.Server.Builder.class);
  }

  private int bitField0_;
  public static final int DOMAIN_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList domain_;
  /**
   * <code>repeated string domain = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDomainList() {
    return domain_;
  }
  /**
   * <code>repeated string domain = 1;</code>
   */
  public int getDomainCount() {
    return domain_.size();
  }
  /**
   * <code>repeated string domain = 1;</code>
   */
  public java.lang.String getDomain(int index) {
    return domain_.get(index);
  }
  /**
   * <code>repeated string domain = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDomainBytes(int index) {
    return domain_.getByteString(index);
  }

  public static final int SETTINGS_FIELD_NUMBER = 2;
  private com.v2ray.core.common.serial.TypedMessage settings_;
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
   */
  public boolean hasSettings() {
    return settings_ != null;
  }
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
   */
  public com.v2ray.core.common.serial.TypedMessage getSettings() {
    return settings_ == null ? com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : settings_;
  }
  /**
   * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
   */
  public com.v2ray.core.common.serial.TypedMessageOrBuilder getSettingsOrBuilder() {
    return getSettings();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < domain_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domain_.getRaw(i));
    }
    if (settings_ != null) {
      output.writeMessage(2, getSettings());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < domain_.size(); i++) {
        dataSize += computeStringSizeNoTag(domain_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDomainList().size();
    }
    if (settings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSettings());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.web.Server)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.web.Server other = (com.v2ray.core.app.web.Server) obj;

    boolean result = true;
    result = result && getDomainList()
        .equals(other.getDomainList());
    result = result && (hasSettings() == other.hasSettings());
    if (hasSettings()) {
      result = result && getSettings()
          .equals(other.getSettings());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getDomainCount() > 0) {
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomainList().hashCode();
    }
    if (hasSettings()) {
      hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getSettings().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.web.Server parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.web.Server parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.web.Server parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.web.Server parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.web.Server parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.web.Server parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.web.Server parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.web.Server parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.web.Server parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.web.Server parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.web.Server prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.app.web.Server}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.web.Server)
      com.v2ray.core.app.web.ServerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.web.ConfigOuterClass.internal_static_v2ray_core_app_web_Server_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.web.ConfigOuterClass.internal_static_v2ray_core_app_web_Server_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.web.Server.class, com.v2ray.core.app.web.Server.Builder.class);
    }

    // Construct using com.v2ray.core.app.web.Server.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      domain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (settingsBuilder_ == null) {
        settings_ = null;
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.web.ConfigOuterClass.internal_static_v2ray_core_app_web_Server_descriptor;
    }

    public com.v2ray.core.app.web.Server getDefaultInstanceForType() {
      return com.v2ray.core.app.web.Server.getDefaultInstance();
    }

    public com.v2ray.core.app.web.Server build() {
      com.v2ray.core.app.web.Server result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.v2ray.core.app.web.Server buildPartial() {
      com.v2ray.core.app.web.Server result = new com.v2ray.core.app.web.Server(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        domain_ = domain_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.domain_ = domain_;
      if (settingsBuilder_ == null) {
        result.settings_ = settings_;
      } else {
        result.settings_ = settingsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.web.Server) {
        return mergeFrom((com.v2ray.core.app.web.Server)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.web.Server other) {
      if (other == com.v2ray.core.app.web.Server.getDefaultInstance()) return this;
      if (!other.domain_.isEmpty()) {
        if (domain_.isEmpty()) {
          domain_ = other.domain_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureDomainIsMutable();
          domain_.addAll(other.domain_);
        }
        onChanged();
      }
      if (other.hasSettings()) {
        mergeSettings(other.getSettings());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.v2ray.core.app.web.Server parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.v2ray.core.app.web.Server) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList domain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDomainIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        domain_ = new com.google.protobuf.LazyStringArrayList(domain_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDomainList() {
      return domain_.getUnmodifiableView();
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public int getDomainCount() {
      return domain_.size();
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public java.lang.String getDomain(int index) {
      return domain_.get(index);
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes(int index) {
      return domain_.getByteString(index);
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public Builder setDomain(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDomainIsMutable();
      domain_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public Builder addDomain(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDomainIsMutable();
      domain_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public Builder addAllDomain(
        java.lang.Iterable<java.lang.String> values) {
      ensureDomainIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, domain_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public Builder clearDomain() {
      domain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string domain = 1;</code>
     */
    public Builder addDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDomainIsMutable();
      domain_.add(value);
      onChanged();
      return this;
    }

    private com.v2ray.core.common.serial.TypedMessage settings_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder> settingsBuilder_;
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public boolean hasSettings() {
      return settingsBuilder_ != null || settings_ != null;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public com.v2ray.core.common.serial.TypedMessage getSettings() {
      if (settingsBuilder_ == null) {
        return settings_ == null ? com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : settings_;
      } else {
        return settingsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public Builder setSettings(com.v2ray.core.common.serial.TypedMessage value) {
      if (settingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settings_ = value;
        onChanged();
      } else {
        settingsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public Builder setSettings(
        com.v2ray.core.common.serial.TypedMessage.Builder builderForValue) {
      if (settingsBuilder_ == null) {
        settings_ = builderForValue.build();
        onChanged();
      } else {
        settingsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public Builder mergeSettings(com.v2ray.core.common.serial.TypedMessage value) {
      if (settingsBuilder_ == null) {
        if (settings_ != null) {
          settings_ =
            com.v2ray.core.common.serial.TypedMessage.newBuilder(settings_).mergeFrom(value).buildPartial();
        } else {
          settings_ = value;
        }
        onChanged();
      } else {
        settingsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public Builder clearSettings() {
      if (settingsBuilder_ == null) {
        settings_ = null;
        onChanged();
      } else {
        settings_ = null;
        settingsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public com.v2ray.core.common.serial.TypedMessage.Builder getSettingsBuilder() {
      
      onChanged();
      return getSettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    public com.v2ray.core.common.serial.TypedMessageOrBuilder getSettingsOrBuilder() {
      if (settingsBuilder_ != null) {
        return settingsBuilder_.getMessageOrBuilder();
      } else {
        return settings_ == null ?
            com.v2ray.core.common.serial.TypedMessage.getDefaultInstance() : settings_;
      }
    }
    /**
     * <code>optional .v2ray.core.common.serial.TypedMessage settings = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder> 
        getSettingsFieldBuilder() {
      if (settingsBuilder_ == null) {
        settingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.v2ray.core.common.serial.TypedMessage, com.v2ray.core.common.serial.TypedMessage.Builder, com.v2ray.core.common.serial.TypedMessageOrBuilder>(
                getSettings(),
                getParentForChildren(),
                isClean());
        settings_ = null;
      }
      return settingsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.web.Server)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.web.Server)
  private static final com.v2ray.core.app.web.Server DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.web.Server();
  }

  public static com.v2ray.core.app.web.Server getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Server>
      PARSER = new com.google.protobuf.AbstractParser<Server>() {
    public Server parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Server(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Server> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Server> getParserForType() {
    return PARSER;
  }

  public com.v2ray.core.app.web.Server getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

