// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/proxy/freedom/config.proto

package com.v2ray.core.proxy.freedom;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.freedom.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .v2ray.core.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
   */
  int getDomainStrategyValue();
  /**
   * <code>optional .v2ray.core.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
   */
  com.v2ray.core.proxy.freedom.Config.DomainStrategy getDomainStrategy();

  /**
   * <code>optional uint32 timeout = 2;</code>
   */
  int getTimeout();

  /**
   * <code>optional .v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
   */
  boolean hasDestinationOverride();
  /**
   * <code>optional .v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
   */
  com.v2ray.core.proxy.freedom.DestinationOverride getDestinationOverride();
  /**
   * <code>optional .v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
   */
  com.v2ray.core.proxy.freedom.DestinationOverrideOrBuilder getDestinationOverrideOrBuilder();
}
